name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole redondear_csv.py

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: redondear_csv_exe
          path: dist/redondear_csv.exe
